---
- name: Recover Machine Config
  hosts: bastion
  vars_file:
   - examples/mc_vars.yml 
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  become_user: root
  gather_facts: no
  roles: 
  - recover-machine-config
