---
- name: "check machine-config failure"
  shell: "./oc adm upgrade"
  register: check_machine_config
  changed_when: false

- name: recover machine config
  #when: '"has not yet successfully rolled out" in check_machine_config.stdout'
  when: '"VERSION" in check_machine_config.stdout'
  block:  
  - debug:
      msg: "Running recover machine config"

  - name: "query machine config"
    shell: "./oc get mc"
    register: machine_config
    changed_when: false

  - name: "get list of master nodes"
    shell: ./oc get nodes -l node-role.kubernetes.io/master="" -o name
    register: master_nodes
    changed_when: false

  - name: "touch machine config daemon file on each master node"
    shell: echo "./oc debug {{ item }} -- chroot /host touch /run/machine-config-daemon-force"
    with_items: "{{ master_nodes.stdout_lines }}"

  - name: "patch machine config on each master node"
    shell: ../roles/recovery-machine-config/files/recover-machine-config.sh {{ machine_config }}
    register: recover_machine_config
