---

- hosts: all
  gather_facts: true
  vars_files:
  - "{{ password_file }}"
  vars:
  - ansible_ssh_common_args: -o StrictHostKeyChecking=no
  - ansible_user: root
  roles:
  - role: nestuser
  - role: osprereqs
  - role: fix_fyre_hosts_file
  - role: timezone
  - role: authorized_keys
