---
    - name: clean up previous repo
      ansible.builtin.file:
        path: "/{{ local_repo_location }}/{{ repo_name }}"
        state: absent

    - name: cloning your github repo {{ repo_name }}
      git:
       repo: "{{ repo_url }}"
       version: "{{ repo_branch }}"
       dest: "/{{ local_repo_location }}/{{ repo_name }}"
       key_file: "{{ ssh_private_key_file }}"
       accept_hostkey: yes
       force: yes