# © Copyright IBM Corporation 2020
#
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
- name: Stop instances using AWS CLI
  shell: |
    aws ec2 stop-instances --region {{ aws_region }} --instance-ids $(aws ec2 describe-instances --filters Name=tag:cluster,Values="{{ cluster_name }}*" Name=tag:owner,Values="{{ cluster_owner }}" --query "Reservations[*].Instances[*].InstanceId" --region {{ aws_region }} --output text)
  register: aws_cli_result
  ignore_errors: yes

- name: Exiting the ansible playbook if rc is not 0
  fail:
    msg: "Cluster not found. Please check the cluster exists in AWS for this region: https://{{ aws_region }}.console.aws.amazon.com/vpc/home?region={{ aws_region }}#vpcs:sort=tag:cluster, or cluster owner was not valid"
  when: aws_cli_result.rc != 0