---
- name: Provision OCP Cluster from hive
  hosts: hive_instance
  vars:
    cloud: vsphere
    device_name: sdb

  vars_files:
    - common-vars.yml
    - vsphere-vars.yml

  environment:
    PATH: ".:{{ ansible_env.PATH }}"

  roles:
    # used to login into RHACM/HIVE cluster
    - role: oc_client_install

    - role: ocp_login

    - role: aws_route53
      when: 'admin_task != "delete"'

    - role: provision_ocp_cluster


  tasks:

    - set_fact:
        route_task: "delete"
      when: 'admin_task == "delete"'

    - name: Run aws_route53 delete - vsphere only
      include_role:
        name: aws_route53
      when: 'route_task == "delete"'

- name: "Using new host connect to new vmware cluster"
  hosts: ocp_provisioned_cluster
  gather_facts: yes
  vars:
    device_name: sdb

  vars_files:
    vsphere-vars.yml

  environment:
    PATH: ".:{{ ansible_env.PATH }}"

  roles:

    - role: ocp_login # claimed cluster login
      when: admin_task != "delete"

    - role: deploy_vmdisk_vmware
      when: admin_task != "delete"

    - role: csi_cephfs
      when: admin_task != "delete"

  tasks:

    - name: logout of cluster
      shell: "oc logout"
      register: logout_results
      ignore_errors: yes
      when: admin_task != "delete"
