---
- name: Provision OCP Cluster from hive
  hosts: hive_instance
  vars:
    cloud: vsphere
    device_name: sdb
    LABEL: "content: build"

  vars_files:
    - common-vars.yml
    - vsphere-vars.yml

  environment:
    PATH: ".:{{ ansible_env.PATH }}"

  roles:
    # used to login into RHACM/HIVE cluster
    - role: oc_client_install

    - role: ocp_login

    - role: aws_route53
      when: 'admin_task != "delete"'

    - role: provision_ocp_cluster


  tasks:

    - name: Display cluster details
      command: cat {{ CLUSTER_NAME }}_details.log
      register: cluster_details
      when: 'admin_task == "provision"'

    - name: Print details
      debug:
        msg: "{{ cluster_details.stdout }}"
      when: 'admin_task == "provision"'

    - set_fact:
        route_task: "delete"
      when: 'admin_task == "delete"'

    - name: Run aws_route53 delete - vsphere only
      include_role:
        name: aws_route53
      when: 'route_task == "delete"'

    - name: Clean kubevols - vsphere only
      include_role:
        name: clean_vmware_kubevols
      when: 'route_task == "delete"'
