---
sudo: true
dist: bionic
os: linux

before_install:
  - sudo apt -y update 
  - sudo apt -y install python3 python3-pip 
  - pip3 install --upgrade pip

install:
  # Install Ansible.
  - pip3 install ansible
  - pip3 install ansible-lint


script:
  # Check the role/playbook's syntax.
  - ansible-lint -i ansible/ocp-pool-claim-play/examples/inventory ansible/ocp-pool-claim-play/ocp-pool-claim-play.yml

