---
# tasks ocs  install

- name: Create ocs setup directory
  file:
    path: "{{ ocs_bastion_setup_dir }}"
    state: "{{ item }}"
    mode: '0755'
  with_items:
  - directory

- name: Get ocs version major.minor
  shell: bash -lc "oc version | grep Server | rev | cut -f1 -d' '| cut -f1 -d'.' --complement| rev "
  register: oc_version

- name: Get localstore version
  shell: bash -lc "echo 4.5"
  when: oc_version.stdout is version('4.5', '<=')
  register: localstore_version

- set_fact:
    local_storage_namespace: openshift-local-storage
  when: oc_version.stdout is version('4.6', '<=')

- name: Viewing local_storage_namespace
  debug:
    msg: "Openshift local_storage_namespace is {{ local_storage_namespace }}"

- name: Get ocs channel
  shell: bash -lc "if [ {{ oc_version.stdout }} == 4.6 ]; then echo 'stable-4.6'; else echo 'stable-4.5'; fi"
  register: ocs_channel

- name: Generate OCS install files
  template:
    src: "{{ item }}.j2"
    dest: "{{ ocs_bastion_setup_dir }}/{{ item }}"
    mode: '0755'
  with_items:
  - 01.ocs-operator.yaml
  - 02.local-storage-operator.yaml
  - 03.local-volumes.yaml
  - 04.storage-cluster.yaml
  - 05.set-default-storageclass.sh

- name: Copy ocs scripts to dest
  copy:
    src: files/
    dest: "{{ ocs_bastion_setup_dir }}/"
    mode: '0755'

- name: Install labels
  shell: bash -lc "{{ ocs_bastion_setup_dir }}/00.label-nodes.sh"
  args:
      warn: false
  register: installlabels

- name: Viewing labels install log
  debug:
    msg: "{{ installlabels.stdout_lines }}"

- name: Install ocs operator
  shell: bash -lc "{{ ocs_bastion_setup_dir }}/01.install-ocs-operator.sh"
  args:
      warn: false
  register: ocsoperator

- name: Viewing ocs operator install log
  debug:
    msg: "{{ ocsoperator.stdout_lines }}"

- name: Install local-storage-operator
  shell: bash -lc "{{ ocs_bastion_setup_dir }}/02.install-local-storage-operator.sh"
  args:
      warn: false
  register: localstore

- name: Viewing local-storage-operator log
  debug:
    msg: "{{ localstore.stdout_lines }}"

- name: Install local-volumes
  shell: bash -lc "{{ ocs_bastion_setup_dir }}/03.install-local-volumes.sh"
  args:
      warn: false
  register: localvolumes

- name: Viewing local-volumes log
  debug:
    msg: "{{ localvolumes.stdout_lines }}"

- name: Install storage storagecluster
  shell: bash -lc "{{ ocs_bastion_setup_dir }}/04.install-storage-cluster.sh"
  args:
      warn: false
  register: storagecluster

- name: Viewing storage cluster log
  debug:
    msg: "{{ storagecluster.stdout_lines }}"

- name: Set default storageclass to ocs-storagecluster-cephfs {{ setdefault }}
  shell: bash -lc "{{ ocs_bastion_setup_dir }}/05.set-default-storageclass.sh"
  args:
      warn: false
  register: storageclass

- name: Viewing set default storageclass log
  debug:
    msg: "{{ storageclass.stdout_lines }}"
