---
# tasks ocs  install

- name: Create ocs setup directory
  file:
    path: "{{ ocs_bastion_setup_dir }}"
    state: "{{ item }}"
    mode: '0755'
  with_items:
  - directory

- name: Copy ocs 4.5 scripts to dest
  copy:
    src: files/
    dest: "{{ ocs_bastion_setup_dir }}/"
    mode: '0755'

- name: Install ocs from channel {{ ocs_channel }}
  shell: bash -lc "{{ ocs_bastion_setup_dir }}/install_all.sh"
  args:
      warn: false
  register: ocsinstall

- name: Viewing ocs install log
  debug:
    msg: "{{ ocsinstall.stdout_lines }}"
