---
# tasks ocs  install

- name: Create ocs setup directory
  file:
    path: "{{ ocs_bastion_setup_dir }}"
    state: "{{ item }}"
    mode: '0755'
  with_items:
  - directory

- name: Copy ocs 4.5 scripts to dest
  copy:
    src: files/
    dest: "{{ ocs_bastion_setup_dir }}/"
    mode: '0755'

- name: Install labels
  shell: bash -lc "{{ ocs_bastion_setup_dir }}/00.label-nodes.sh"
  args:
      warn: false
  register: installlabels

- name: Viewing labels install log
  debug:
    msg: "{{ installlabels.stdout_lines }}"

- name: Install ocs operator
  shell: bash -lc "{{ ocs_bastion_setup_dir }}/01.install-ocs-operator.sh"
  args:
      warn: false
  register: ocsoperator

- name: Viewing ocs operator install log
  debug:
    msg: "{{ ocsoperator.stdout_lines }}"

- name: Install local-storage-operator
  shell: bash -lc "{{ ocs_bastion_setup_dir }}/02.install-local-storage-operator.sh"
  args:
      warn: false
  register: localstore

- name: Viewing local-storage-operator log
  debug:
    msg: "{{ localstore.stdout_lines }}"


- name: Install local-volumes
  shell: bash -lc "{{ ocs_bastion_setup_dir }}/03.install-local-volumes.sh"
  args:
      warn: false
  register: localvolumes

- name: Viewing local-volumes log
  debug:
    msg: "{{ localvolumes.stdout_lines }}"

- name: Install storage cluster
  shell: bash -lc "{{ ocs_bastion_setup_dir }}/04.install-storage-cluster.sh"
  args:
      warn: false
  register: storagecluster

- name: Viewing storage cluster install log
  debug:
    msg: "{{ storagecluster.stdout_lines }}"
