---
- hosts: fyreApi
  roles: 
  - role: request_ocp_fyre

- hosts: ocp-clusters
  gather_facts: false
  tasks:
  - name: Check machine alive
    raw: echo "hello im running on the inf node"
    changed_when: false
