---
- name: create install-config
  template:
    src: "{{ cloud }}-install-config-template.j2"
    dest: "/tmp/{{ CLUSTER_NAME }}/install-config.yaml"
    backup: false
  register: template_results

- name: Provision cluster
  shell: "openshift-install create cluster --dir=/tmp/{{ CLUSTER_NAME }}/install-config.yaml | tee /tmp/{{ CLUSTER_NAME }}/log/provision.log"
  async: 3600
  poll: 0
  register: provision_results

- name: Check provisioning, wait up to 1 hour
  async_status:
    jid: "{{ provision_results.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 60
  delay: 60
  failed_when: job_result.finished != 1
