---
    - name: check pods readiness
      shell: "oc --no-headers=true get pods --all-namespaces | grep -v -E \"Comp|Run\""
      register: pod_check
      until: 'pod_check.stdout == ""'
      retries: 30
      delay: 60

    - name: execute post install
      shell: "pushd .; cd {{ script_location }}; {{ script_command }}; popd"
      args:
        executable: /bin/bash
      register: post_results
      until: 'post_results.stdout.find("{{ success_message }}") != -1'
      retries: 60
      delay: 60