---
- name: Destroy cluster
  shell: " echo openshift-install destroy cluster --dir=/tmp/{{ CLUSTER_NAME }}/install-config.yaml | tee /tmp/{{ CLUSTER_NAME }}/log/provision.log"
  async: 1800
  poll: 0
  register: destroy_results

- name: Check destroy, wait up to 30
  async_status:
    jid: "{{ delete_results.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30
  delay: 60
  failed_when: job_result.finished != 1
