---

- name: Provision OCP cluster
  when: 'admin_task == "provision"'
  block: 
  - name: create clusterdeployment CR based on template
    template:
      src: "{{ cloud }}-template.j2"
      dest: "{{ cloud }}-clusterdeployment-cr.yml"
      backup: true
    register: template_results

  - name: Create Namespace based on cluster name
    shell: "oc create namespace {{ cluster_name }}"
    register: ns_results

  - name: Apply provision yaml to ACM/Hive cluster
    shell: "oc apply -f  {{ cloud }}-clusterdeployment-cr.yml"
    register: provision_results

  - name: Get the provisioning pod name
    shell:  oc --no-headers=true get pods -n {{ CLUSTER_NAME }} -l "hive.openshift.io/job-type=provision,hive.openshift.io/cluster-deployment-name={{ CLUSTER_NAME }}" -o name
    register: pro_pod_results
    set_fact: 
      provision_podname: "{{ pro_pod_results.stdout }}"

  - name: Monitor provisioning progress
    shell: oc logs -n ocp-461-ansible  -f "{{ provision_podname }}" -c hive
    register: monitor_results
    until: monitor_result.stdout.find("install completed successfully") != -1
    retries: 10
    delay: 60

- name: Deleting OCP cluster
  when: 'admin_task == "delete"'
  block:
   - name: Delete cluster
     shell: "oc -n {{ CLUSTER_NAME }} delete clusterdeployment {{ CLUSTER_NAME }} --wait=false"
     register: delete_results
  
   - name: Check for cluster removal
     shell: oc get clusterdeployment {{ CLUSTER_NAME }} -n {{ CLUSTER_NAME }}
     register: check_cluster_results
     until: check_cluster_results.rc != 0

   - name: Deleting namespace
     shell: oc delete namespace "{{ CLUSTER_NAME }}" 
     register: delete_ns_results

