---
# specific OS supports wildcards
- name: remove current OS instana packages
  become: yes
  ignore_errors: yes
  apt:
   name: "{{ packages }}"
   state: absent
   autoremove: yes
  vars:
   packages:
   - "instana-agent-dynamic"
   - "instana-agent-dynamic-j9"
   - "instana-agent-static"
   - "instana-agent-static-j9"
