---

- hosts: all
  vars:
  - ansible_user: "{{ jmeterUser }}"
  - javaDir: "/home/{{ jmeterUser }}/java"
  - jmeterDir: "/home/{{ jmeterUser }}/jmeter"
  roles:
  - role: jmeter_java
  - role: jmeter

