---
  - name: "Claim an OCP cluster from pool"
    hosts: hive_instance
    gather_facts: yes
    vars_files:
      - pool-vars.yml

    environment:
      PATH: ".:{{ ansible_env.PATH }}"

    roles:
      - oc-client-install
      - ocp-login # login to hive cluster
      - ocp_pool_claim

  - name: "setup claimed ocp cluster"
    hosts: ocp_claimed_cluster
    vars_files:
      - custom-vars.yml

    environment:
      PATH: ".:{{ ansible_env.PATH }}"

    roles:
      - ocp-login # cluster claim
        when: 'post_install == "true" and admin_task == "claim"' 
      - request-ocs
        when: 'ocs_storage == "true" and admin_task == "claim"' 
      - post_install
        when: 'admin_task == "claim" and post_install == "true"' 
        