---
  - name: "Claim an OCP cluster from pool"
    hosts: hive_instance
    gather_facts: yes
    vars_files:
      - pool-vars.yml

    environment:
      PATH: ".:{{ ansible_env.PATH }}"

    roles:
      - oc-client-install
      - ocp-login # login to hive cluster
      - ocp_pool_claim

  - name: "setup claimed ocp cluster"
    hosts: ocp_claimed_cluster
    vars_files:
      - custom-vars.yml

    environment:
      GITHUB_TOKEN: "{{ GITHUB_TOKEN }}"
      GITHUB_USER: "{{ GITHUB_USER }}"
      PATH: ".:{{ ansible_env.PATH }}"

    roles:
      - role: ocp-login # claimed cluster login
        when: post_install == "true" and admin_task == "claim"

      - role: request-ocs
        when: ocs_storage == "true" and admin_task == "claim"

      - role: clone_repo
        when: post_install == "true" and admin_task == "claim"

      - role: post_install
        when: post_install == "true" and admin_task == "claim"        