---

- name: set jmeter host specs
  no_log: "{{ noLog }}"
  vars:
  ## crc host specs
  - arch: x
  - numcpu: 16
  - memory: 64 # GB memory Fyre hosting VM
  - disksizegb: 550 # extra DB
  - fos: 'Ubuntu 18.04'
  - comment: 'Instana Host'
  - localclusterName: "{{ clusterName }}"
  include_tasks:
    file: instana_fyrevm.yml
