---
  - name: "{{ admin_task }} an {{ cloud }} cluster"
    hosts: bastion
    vars_files:
      - admin-vars.yml
    roles:
      - "{{ cloud }}-cli-install"
      - "{{ admin_task }}-{{ cloud }}-cluster"
