---
  - name: "{{ admin_task }} an {{ cloud }} cluster"
    hosts: bastion
    vars_files:
      - admin-vars.yml
    environment:
      AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    roles:
      - "{{ cloud }}-cli-install"
      - "{{ admin_task }}-{{ cloud }}-cluster"
