rook_cephfs_release: v1.3.8 #Rook-ceph release from https://github.com/rook/rook/releases
rendered_sc: "csi-cephfs" #Storageclass to use for ocp logging PVCs. If left empty will use the designated default storageclass.
ocp_logging_version: 4.2 #Ocp logging version
