#
# Copyright 2020- IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#
---
collections:
  - name: community.okd
    version: 1.0.1
  - name: community.general
  - name: community.kubernetes
    version: 1.1.1

