---
- name: Download OCP CLI
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_client_version }}/openshift-client-{{ arch }}-{{ ocp_client_version }}.tar.gz
    dest: "./openshift-client.tar.gz"
    validate_certs: false
  vars:
    arch: "{{ 'mac' if ansible_distribution == 'MacOSX' else 'linux' }}"
    
- name: Unpack OCP CLI
  shell: |
    tar xf "openshift-client.tar.gz" oc kubectl
    chmod 0755 oc kubectl
  args:
    # Suppress the warning about using 'tar'
    warn: false