---
# Download from URL oav and deploy to vCenter
- name: Get number of worker nodes
  shell: "oc get no | tr -s ' ' | cut -f1 -d' ' | grep worker | wc -l"
  register: num_worker_nodes

- name: Ingress router Get number of worker nodes
  shell: "oc patch -n openshift-ingress-operator ingresscontroller/default --patch \"{\"spec\":{\"replicas\": {{ num_worker_nodes.stdout }} }}\" --type=merge"
  args:
      warn: false
  register: ingress_routes

- name: Viewing Waiting for rook-ceph-mds-myfs pods to go to Running Log
  debug:
    msg: "{{ ingress_routes.stdout_lines }}"
