---
# Master nodes 
"MASTER_CPUS": "10"
"MASTER_MEMORY": "32768"
"MASTER_DISK_SIZE": "300"
"MASTER_COUNT": 3

# Worker nodes
"WORKER_COUNT": 3
"WORKER_CPUS": "16"
"WORKER_MEMORY": "73728"
"WORKER_DISK_SIZE": "200"
"WORKER_DISK2_SIZE": "500"   # For cephfs

#Cephfs deply - No changes needed
rook_cephfs_release: v1.6.8  # Rook-ceph release from https://github.com/rook/rook/releases
default_sc: file-storage
