#
# Copyright 2020- IBM Inc. All rights reserved
# SPDX-License-Identifier: Apache2.0
#
---
- name: Install DB2 Community Edition on fyre
  hosts: localhost
  module_defaults:
    community.okd.openshift_auth:
          host: "{{ ocp_api_url }}"
          validate_certs: no
    group/k8s:
      host: "{{ ocp_api_url }}"
      validate_certs: no
    community.general.oc:
      host: "{{ ocp_api_url }}"
      validate_certs: no
  gather_facts: no
  roles:
    - role: db2_fyre