---

- name: set crc host specs
  no_log: "{{ noLog }}"
  vars:
  ## crc host specs
  - arch: x
  - numcpu: 6
  - memory: 32 # GB memory Fyre hosting VM
  - fos: 'Redhat 8.2'
  - comment: 'RH OpenShift crc'
  - localclusterName: "{{ clusterName }}"
  include_tasks:
    file: crc_fyrevm.yml
