---
- name: add AWS tags to cluster
  when: 'cloud == "aws"'
  block:
  - name: Calling aws client to add tags
    shell: "aws ec2 create-tags --tags \
    Key={{ cluster_tag }},Value={{ cluster_tag_value }} \
    Key={{ owner_tag }},Value={{ owner_tag_value }} \
    Key={{ team_tag }},Value={{ team_tag_value }} \
    Key={{ usage_tag }},Value={{ usage_tag_value }} \
    Key={{ usage_description_tag }},Value=\"{{ usage_description_tag_value }}\" \
    Key={{ review_tag }},Value={{ review_tag_value }} \
    --region {{ AWS_REGION }}  --resources $(aws ec2 describe-instances \
    --filters Name=tag:Name,Values={{ cluster_tag_value }}* \
    --query Reservations[*].Instances[*].InstanceId \
    --region {{ AWS_REGION }}  --output text)"
    register: add_aws_tags_results

- name: add Google tags to cluster
  when: 'cloud == "google"'
  block:
  vars: 
    service_account_file: /workspace/creds.gcp.json
    project: ashworth-test
    auth_kind: serviceaccount
    scopes: "https://www.googleapis.com/auth/compute"

  - name: Allocate an IP Address
    gcp_compute_address:
      state: present
      name: 'test-address1'
      region: 'us-west1'
      project: "{{ project }}"
      auth_kind: "{{ auth_kind }}"
      service_account_file: "{{ service_account_file }}"
      scopes: "{{ scopes }}"

  - name: Calling google client to add tags
    shell: "echo calling google client..."
    register: google_client_results

- name: add Azure tags to cluster
  when: 'cloud == "azure"'
  block:
  - name: Calling azure client to add tags
    shell: "echo calling azure client..."
    register: azure_client_results

- name: add ibmcloud tags to cluster
  when: 'cloud == "ibmcloud"'
  block:
  - name: Calling ibmcloud client to add tags
    shell: "echo calling ibmcloud client..."
    register: ibmcloud_client_results