---
- name: add AWS tags to cluster
  when: 'cloud == "aws"'
  block:
  - name: get instances based on tag Name (CLUSTER_NAME)
    community.aws.ec2_instance_info:
      filters:
        "tag:Name": "{{ CLUSTER_NAME }}"
    register: tag_results

  - name: add tags
    amazon.aws.ec2_tag:
      region: '{{ region }}'
      resource: '{{ item.instance_id }}'
      state: present
      tags:
        "{{ my_cluster_tags }}"
    loop: '{{ tag_results.instances }}'
    loop_control:
      label: '{{ item.instance_id }}'

- name: add Google tags to cluster
  when: 'cloud == "google"'
  block:
  vars: 
    service_account_file: /workspace/creds.gcp.json
    project: ashworth-test
    auth_kind: serviceaccount
    scopes: "https://www.googleapis.com/auth/compute"

  - name: Allocate an IP Address
    gcp_compute_address:
      state: present
      name: 'test-address1'
      region: 'us-west1'
      project: "{{ project }}"
      auth_kind: "{{ auth_kind }}"
      service_account_file: "{{ service_account_file }}"
      scopes: "{{ scopes }}"

  - name: Calling google client to add tags
    community.general.gce_labels:
      labels: { label1: test, label2: test2 }
    register: google_client_results

- name: add Azure tags to cluster
  when: 'cloud == "azure"'
  block:
  - name: Calling azure client to add tags
    shell: "echo calling azure client..."
    register: azure_client_results

- name: add ibmcloud tags to cluster
  when: 'cloud == "ibmcloud"'
  block:
  - name: Calling ibmcloud client to add tags
    shell: "echo calling ibmcloud client..."
    register: ibmcloud_client_results