---
# ACM/HIVE Cluster Information
"kubeadmin_user": "kubeadmin"
"kubeadmin_password": "" # AWS public ACM/Hive Instance aquired from content devops team
"ocp_api_url": "api.rhacm-public-cluster.purple-chesterfield.com" # AWS public ACM api URL

"CLUSTER_NAME": "<cluster_name>"

# cluster tagging details the following detailed tags are used by the weekly cleanup scripts.  If your
# cluster is not under the account that is affected by the cleanup script you can use whatever tags you want 
# by following the same structure shown in the example
# "owner_tag": "owner" # owner| Owner (Azure)
# "owner_tag_value": "email address" # for Google clusters use FirstNameLastName
# "cluster_tag": "CLUSTER_NAME"  # this tag will be used by the Stop/Start community jenkins job.
# "team_tag": "team" # "Team" when Azure"
#  values: "DBA|Content|CP4MCM|CP4I|Edge|CP4Apps|Netcool"
# "Usage:" 
#   values:  "temp|demo|infra (long term use, must be reviewed regularly)"
# "Usage_desc:"
# "Review_freq:" or "Delete_date:" (Azure)
#   values: "3day|week|month|quarter|half|YYYY-MM-DD (Azure)"
#
# content team tags "{ cluster: {{ CLUSTER_NAME }}, owner: someone@us.ibm.com, team: Content, Usage: temp, Usage_desc: your_description, Review_frequency: week }"
"cluster_tags": { cluster: "{{ CLUSTER_NAME }}", owner: someone@us.ibm.com }

# Deployment Details
"admin_task": "provision" # delete|provision
"cloud": "aws"  # aws|google|azure|vsphere (AWS only at the moment)
"SSH_PUBLIC_KEY": "<public key>"
"BASE_DOMAIN": "purple-chesterfield.com"
"OCP_RELEASE_IMAGE": "quay.io/openshift-release-dev/ocp-release:4.6.8-x86_64"
"PULL_SECRET": '<pull_secret>' # be sure to leave the quotes in place
