---
# any or all of these can be passed on the ansible-playbook command line using -e "var=value" 
# ACM/HIVE Cluster Information
"kubeadmin_user": "kubeadmin"
"kubeadmin_password": "" # RHACM/Hive Instance aquired from content devops team
"ocp_api_url": "api.hive2.purple-chesterfield.com" #  RHACM/Hive api URL

# pool options
"admin_task": ""  # claim|release can be easier to pass and param to playbook, -e "admin_task=claim"
"pool_name": ""   # the name of the cluster pool, predefined in RHACM/hive cluster
"pool_namespace": ""   # the cluster pool namespace, predefined in RHACM/hive cluster
"claim_name": ""   # a unique name of your choice