---
  - name: "{{ admin_task }} an {{ cloud }} cluster"
    hosts: bastion
    gather_facts: no
    vars_files:
      - tag-vars.yml
    environment: 
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
      AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    roles:
      - "{{ cloud }}-cli-install"
      - ocp-cluster-tag