---
- name: Provision OCP Cluster using IPI
  hosts: bastion
  vars:
    cloud: aws

  vars_files:
    - common-vars.yml
    - aws-vars.yml

  environment:
    PATH: ".:{{ ansible_env.PATH }}"
    AWS_ACCESS_KEY_ID: "aws_access_key_id"
    AWS_SECRET_ACCESS_KEY: "aws_secret_access_key"

  roles:
    - role: oc_client_install
    - role: get_ocp_installer
    - role: ipi_ocp_cluster_provision

- name: "Using new OCP cluster"
  hosts: ocp_provisioned_cluster
  gather_facts: yes
  vars:
    kubeconfig_location: "/tmp/{{ CLUSTER_NAME }}/"

  vars_files:
    - common-vars.yml
    - aws-vars.yml
  
  environment:
    PATH: ".:{{ ansible_env.PATH }}"

  roles:
    - role: ocp_login # new cluster login

  tasks:
    - name: logout of cluster
      shell: "oc logout"
      register: logout_results
      ignore_errors: yes
