---
- name: check if aixtoolbox is installed
  stat:
   path: /usr/bin/yum 
  register: istoolbox

- block:
        # FAILS with ssl3 comm error
        #  - name: get aixtoolbox get_url
        #    get_url:
        #     url: "https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/ezinstall/ppc/yum_bundle.tar"
        #     dest: /tmp
        #     validate_certs: false
        #    become: yes

        #  - name: get aixtoolbox
        #    unarchive:
        #      validate_certs: False
        #      src: "https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/ezinstall/ppc/yum_bundle.tar"
        #      dest: /tmp
        #      remote_src: yes
        #    become: yes
        #
  - name: create aixtoolbox dir
    file:
     path: /tmp/aixtoolbox
     state: directory
  - name: get aixtoolbox get_url
    get_url:
     url: "http://nest-reports1.fyre.ibm.com/opt/downloads/yum_bundle.tar"
     dest: /tmp/aixtoolbox
     validate_certs: false
    become: yes
  - name: get aixtoolbox
    command: 'tar -xf yum_bundle.tar'
    args:
     chdir: /tmp/aixtoolbox
    become: yes
  - name: install aixtoolbox rpms
    command: 'rpm -Uvh --force *.rpm'
    args:
     chdir: /tmp/aixtoolbox
    become: yes
  - name: Install the latest version sudo
    yum:
     name: sudo
     state: latest
    become: yes
  when: istoolbox.stat.exists == False
- name: yum update all latest
  yum:
   name: '*'
   state: latest
  become: yes
  register: isupdated
