---

# simple interface with no fancy options should work for any ansible supported OS
- name: remove packages
  become: true
  ignore_errors: true
  action: >
   {{ ansible_pkg_mgr }} state=absent update_cache=yes name=adobe,containers,samba,valgrind

- name: install packages
  become: true
  ignore_errors: true
  action: >
   {{ ansible_pkg_mgr }} state=present update_cache=yes name=zip,unzip
