---
- name: add tags to aws cluster
  shell: "aws ec2 create-tags --tags \
  Key={{ cluster_tag }},Value={{ cluster_tag_value }} \
  Key={{ owner_tag }},Value={{ owner_tag_value }} \
  Key={{ team_tag }},Value={{ team_tag_value }} \
  Key={{ usage_tag }},Value={{ usage_tag_value }} \
  Key={{ usage_description_tag }},Value=\"{{ usage_description_tag_value }}\" \
  Key={{ review_tag }},Value={{ review_tag_value }} \
  --region {{ AWS_REGION }}  --resources $(aws ec2 describe-instances \
  --filters Name=tag:Name,Values={{ cluster_tag_value }}* \
  --query Reservations[*].Instances[*].InstanceId \
  --region {{ AWS_REGION }}  --output text)"
  register: add_tags_results
