### instana dir's are hard coded
instana_dir_custom: '/opt/instana-agent'
instana_dir_normal: '/opt/instana/agent'
get_normal_linux_agent: 'https://setup.instana.io/agent'
agent_key: 'thisIsAllowsOverridden'
instana_host_port: 'thisIsAllowsOverridden'
install_normal_linux_agent: "/opt/setup_agent.sh -a {{ agent_key }} -t dynamic -e {{ instana_host_port }}  -y -s"
custom_agent_url: 'thisIsAllowsOverridden'
