kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  namespace: "{{ nfs_provisioner_namespace }}"
  annotations:
    volume.beta.kubernetes.io/storage-class: "{{ storageClassName }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi