---

- name: Create FyreVM with appropriate spec
  include_role: fyrevm_provision
  fyre_arch: x
  fyre_cpu: 2
  fyre_memory: 2  
  fyre_os: 'Redhat 8.4'
  fyre_site: "{{ site }}"
  fyre_comment: 'RH Jmeter'
  stackName_prefix: crc
  target_group: jmeter
  target_user: "{{ jmeterUser }}"
  extra_props: 
    jmeterUser: "{{ jmeterUser }}"
    vnc: "{{ vnc }}"
