---
- name: Install csi-cephfs on fyre OCP+Beta env
  hosts: bastion
  gather_facts: no
  hosts: bastion
  tasks:
  - name: python_install_fyre
    include_role:
      name: python_install_fyre
  - name: Gathering Facts
    setup:
  - name: git_install_fyre
    include_role: 
      name: git_install_fyre
  - name: csi_cephfs_fyre
    include_role:
      name: csi_cephfs_fyre
